### ISSUE TITLE
Set up Kanban board

### ISSUE THREAD

**Issue by Nelitaa** [gealsanchez/CapstoneModule2#21]
**Team Members:**

1. @gealsanchez 
2. @Nelitaa 

Here you can see the link to our [Kanban board](https://github.com/users/gealsanchez/projects/1/views/1)

**Project requirements**

- Join a Zoom call with your team. Only one person needs to copy the board on behalf of the entire team but everybody should help during the call.
- Create an empty repository for your group project.
- Follow the steps described in [curriculum-tools-copy-projects](https://github.com/microverseinc/curriculum-tools-copy-projects).
- Open the GitHub project (Kanban board) in your team repo.
- Make sure that in the card titles you can see: Student A, Student B, or Student C.
- Make sure that each card starts with [Xpt] - that number indicates the number of points that shows how complex the task is. 1 point = 1 hour of work.
- If your group includes two people - remove all cards with Student C in the title.
- Decide who in your team is the Student A, Student B, or Student C.
- Each of the team members should assign themselves to the correct cards. Decide who will be the assignee for the cards marked as group tasks. All cards on your Kanban board should have assignees.
- [Open a new issue in your repository](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue). In its description, paste a link to your GitHub project.
- Add a note telling the reviewer how many people there are in your team.
- Use the issue link to ask for a review. A Code Reviewer will leave you feedback in the issue's comment.
- As it is your first time using a GitHub project and Kanban board, we need to double-check your setup to avoid problems while working on your project.

**Comment by Nelitaa** [comment]
Done!

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- No linter errors ✔️ 
- Good implementations ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Nelitaa** [comment]
Thanks for reviewing our issue! 😊
